version: '3.1'
services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications_db
    ports:
      - 5454:5432
    # create a volumes to persist data 
    volumes:
      - pg_data:/var/lib/postgres/data
volumes:
  pg_data: